"""Initial migration.

Revision ID: c30504f8ad59
Revises: 
Create Date: 2022-07-01 12:11:31.073361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c30504f8ad59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roll_no', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=60), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['events.meeting_id'], ),
    sa.ForeignKeyConstraint(['name'], ['users.name'], ),
    sa.ForeignKeyConstraint(['roll_no'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.alter_column('users', 'department',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'department',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_table('leave')
    # ### end Alembic commands ###
